services:
  supotsu-backend:
    image: ghcr.io/supotsu-no-ochaya/supotsu-backend:dev
    container_name: supotsu-backend
    ports:
      - "8090:8090"
    volumes:
      - pbdata:/app/pb_data
    environment:
      - PB_SUPERUSER_EMAIL=admin@admin.admin
      - PB_SUPERUSER_PASSWORD=1234567890
volumes:
  pbdata: