# docker compose configuration requires a pb_data folder to be mounted into the container to supply testdata
services:
  supotsu-backend:
#    image: ghcr.io/supotsu-no-ochaya/supotsu-backend:dev
    image: supotsu-backend:local
    container_name: supotsu-backend
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/app/pb_data
