services:
  supotsu-backend:
    image: supotsu-backend:local
    container_name: supotsu-backend
    ports:
      - "8090:8090"
    volumes:
      - pb-data:/app/pb_data
      - config:/app/config
    environment:
      - SUPERUSER_EMAIL=admin@admin.admin
      - SUPERUSER_PASSWORD=1234567890

volumes:
  pb-data:
  config:
