name: Container Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: supotsu-backend
  IMAGE_TAG: dev
  #IMAGE_TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
#            ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.event.inputs.tag }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG
